### ISSUE TITLE
What is this project about? 

### ISSUE THREAD

**Issue by Aluxian** [shwenzhang/AndResGuard#14] opened 2015-10-19 08:29 UTC
Hey everyone, this project looks interesting but I don't understand what it's supposed to do because of the language. Could anyone explain in English, please? Thank you.

**Comment by simpleton** [comment] 2015-10-19 11:12
Inbref, this repo is help you to reduce your android apk's size. It will change your resource path to very short which is like what the proguard do on your source code.

**Comment by simpleton** [comment] 2015-10-19 11:12
#11

**Comment by simpleton** [comment] 2015-10-19 11:17
Duplicate of issue #11

**Closed by simpleton** 2015-10-19 11:17 UTC
